### ISSUE TITLE
RARBG search plugin not working?

### ISSUE THREAD

**Issue by gumpster2010** [b0nk/qbittorrent-search-plugins#1]
Hi b0nk --

Is the RARBG plugin updated? I noticed I'm not getting any RARBG results in my qBittorrent app, even for searches that I know have results on the web page. I would love an update so I can easily search RARBG.

Thanks!

**Comment by b0nk** [comment]
Hello.

I have updated the script a few times could you check now?

**Comment by gumpster2010** [comment]
Hello! Yes it does appear to be working now. Thank you!

**Comment by gorvinsky** [comment]
Hi b0nk, the search plugin is not working.

qBittorrent v4.0.4 (64-bit)
Plugin version 1.13

**Comment by b0nk** [comment]
I am aware of this.
Follow the issue here:
 https://github.com/pacoesteban/Rarbg-torrentapi/issues/3

**Comment by pacoesteban** [comment]
Not sure why you opened the issue to Rarbg-torrentapi, as you're not using it ... This project is in python ...
Anyway, there was indeed a problem. The module was not including the (now) necessary **app_id** parameter. You should do the same in your code.

**Comment by b0nk** [comment]
You're right pacoesteban but I couldn't find anywhere else to report it to.
To anyone wondering, the script is now working again.
