### ISSUE TITLE
I'm trying to get categories working on rarbg

### ISSUE THREAD

**Issue by Pireo** [b0nk/qbittorrent-search-plugins#3]
https://raw.githubusercontent.com/Pireo/hello-world/master/rarbg.py

I've added categories here, but I can't get them work even posting something like 
if cat != 'all':

etc...

**Comment by b0nk** [comment]
Hello, have you had any success yet?
I might try to implement this sometime this week.
And I'll post my progress here.

**Comment by Pireo** [comment]
Not yet, I think we should include a search string where we specify it.

**Comment by b0nk** [comment]
Hey @Pireo I have updated the script please try this new version.

**Comment by Pireo** [comment]
Yes, now it works, thanks!
