### ISSUE TITLE
Faulty version numbering

### ISSUE THREAD

**Issue by hannsen** [b0nk/qbittorrent-search-plugins#4]
You had an old version called 1.13 and now the version is 1.3, which Qbit detects as a lower version ( 3 < 13 )

Just so you know :)

**Comment by b0nk** [comment]
Hmm you're right. What do you suggest? Changing to 2.0 or jumping to 1.20 or something?

**Comment by hannsen** [comment]
I would do 1.20

**Comment by b0nk** [comment]
Fixed in cf5b8f190fd44241e15ffe38bb1459f1d6c7930f
