### ISSUE TITLE
Include rarbg as official qbittorrent plugin

### ISSUE THREAD

**Issue by ngosang** [b0nk/qbittorrent-search-plugins#6]
@b0nk 
Hi, I'm the official maintainer of qbittorrent plugins.
I want to promote this plugin to official. If you are interested:

1. Open a PR here https://github.com/qbittorrent/search-plugins
2. Use the domain https://rarbg.to/ in https://github.com/b0nk/qbittorrent-search-plugins/blob/master/rarbg.py#L42
3. Rename the plugin to "RARBG" in https://github.com/b0nk/qbittorrent-search-plugins/blob/master/rarbg.py#L43
4. Copy the same code to folders `nova` and `nova3`
5. Add it to files `nova/versions.txt` and `nova3/versions.txt`

I will review and merge the code asap.
Thank you

**Comment by b0nk** [comment]
Hello @ngosang.

Very happy to see you guys taking interest in this script.

I'll keep in touch with you and others about this matter in the main discussion when I have the time for it.

There are a few questions I want to address before we go forward with this but I'm sure it'll be fine.

I'll close this issue when the discussion in your repo is over.

See ya there!

**Comment by ngosang** [comment]
Do you give me permission to add it myself?

**Comment by ngosang** [comment]
Implemented here => https://github.com/qbittorrent/search-plugins/pull/48
